
local recipes = {
    {
        Recipe='The Insanely Expensive Method',
        Trivial=335,
        Materials={'Blessed Sickle Hilt','Blessed Sickle Pommel','Blessed Sickle Blade','Mistletoe Cutting Sickle'},
        Container='Forge',
        Tradeskill='Blacksmithing',
    },
    {
        Recipe='The Slightly Less Insane Method',
        Trivial=348,
        Materials={'Banded Gorget','Banded Mail','Rubishot','Fine Plate Visor','Fine Plate Breastplate','Rubicite Plate Gauntlet Template','Ethereal Metal Rings','Shaded Kunai','Indium Plate Gauntlet Template','Rhenium Plate Gauntlet Template','Tungsten Plate Gorget Template','Cobalt Plate Gorget Template'},
        Container='Forge',
        Tradeskill='Blacksmithing',
    },
    {
        Recipe='Custom Recipes',
        Trivial=215,
        Materials={'Shaded Kunai'},
        Container='Forge',
        Tradeskill='Blacksmithing',
    },
    {
        Recipe='Useful Recipes',
        Trivial=300,
        Materials={'Enchanted Alloy Whittling Blade'},
        Container='Forge',
        Tradeskill='Blacksmithing',
    },
}
local subcombines = {
    ['Celestial Essence'] = {
        Recipe='Celestial Essence',
        Trivial=15,
        Yield=1,
        Materials={'Celestial Solvent','The Scent of Marr'},
        Container='Mixing Bowl',
        Tradeskill='Baking',
    },
    ['Mistletoe Temper'] = {
        Recipe='Mistletoe Temper',
        Trivial=136,
        Yield=1,
        Materials={'Celestial Essence','Elven Wine','Mistletoe'},
        Container='Brew Barrel',
        Tradeskill='Brewing',
    },
    ['Blessed Dust of Tunare'] = {
        Recipe='Blessed Dust of Tunare',
        Trivial=103,
        Yield=1,
        Materials={'Celestial Essence','Jar of Acid','Imbued Emerald'},
        Container='Kiln',
        Tradeskill='Pottery',
    },
    ['Blessed Sickle Hilt'] = {
        Recipe='Blessed Sickle Hilt',
        Trivial=180,
        Yield=1,
        Materials={'Celestial Essence','Blessed Dust of Tunare','Mistletoe Temper','Ruby','Smithy Hammer','Sheet Metal','Hilt Mold'},
        Container='Forge',
        Tradeskill='Blacksmithing',
    },
    ['Blessed Sickle Pommel'] = {
        Recipe='Blessed Sickle Pommel',
        Trivial=182,
        Yield=1,
        Materials={'Celestial Essence','Blessed Dust of Tunare','Mistletoe Temper','Sapphire','Smithy Hammer','Sheet Metal','Pommel Mold'},
        Container='Forge',
        Tradeskill='Blacksmithing',
    },
    ['Blessed Sickle Blade'] = {
        Recipe='Blessed Sickle Blade',
        Trivial=183,
        Yield=1,
        Materials={'Celestial Essence','Blessed Dust of Tunare','Mistletoe Temper','Emerald','Smithy Hammer','Sheet Metal','Curved Blade Mold'},
        Container='Forge',
        Tradeskill='Blacksmithing',
    },
    ['Mistletoe Cutting Sickle'] = {
        Recipe='Mistletoe Cutting Sickle',
        Trivial=335,
        Yield=1,
        Materials={'Blessed Sickle Blade','Blessed Sickle Pommel','Blessed Sickle Hilt','Smithy Hammer'},
        Container='Forge',
        Tradeskill='Blacksmithing',
    },
    ['Banded Gorget'] = {
        Recipe='Banded Gorget',
        Trivial=92,
        Yield=1,
        Materials={'Sheet Metal','Gorget Mold','Water Flask'},
        Container='Forge',
        Tradeskill='Blacksmithing',
    },
    ['Banded Mail'] = {
        Recipe='Banded Mail',
        Trivial=115,
        Yield=1,
        Materials={'Sheet Metal','Sheet Metal','Sheet Metal','Mail Sectional Mold','Water Flask'},
        Container='Forge',
        Tradeskill='Blacksmithing',
    },
    ['Rubishot'] = {
        Recipe='Rubishot',
        Trivial=162,
        Yield=20,
        Materials={'Rubicite Ore','File'},
        Container='Forge',
        Tradeskill='Blacksmithing',
    },
    ['Fine Plate Visor'] = {
        Recipe='Fine Plate Visor',
        Trivial=163,
        Yield=1,
        Materials={'Medium Quality Folded Sheet Metal','Smithy Hammer','Water Flask','Leather Padding','Plate Visor Mold'},
        Container='Forge',
        Tradeskill='Blacksmithing',
    },
    ['Fine Plate Breastplate'] = {
        Recipe='Fine Plate Breastplate',
        Trivial=188,
        Yield=1,
        Materials={'Medium Quality Folded Sheet Metal','Medium Quality Folded Sheet Metal','Medium Quality Folded Sheet Metal','Smithy Hammer','Water Flask','Leather Padding','Breastplate Mold'},
        Container='Forge',
        Tradeskill='Blacksmithing',
    },
    ['Rubicite Plate Gauntlet Template'] = {
        Recipe='Rubicite Plate Gauntlet Template',
        Trivial=198,
        Yield=1,
        Materials={'Brown Nitrous Coal','Smithy Hammer','Plate Gauntlet Template Mold','Metal Tempering Chemicals','Rubicite Ore'},
        Container='Forge',
        Tradeskill='Blacksmithing',
    },
    ['Ethereal Metal Rings'] = {
        Recipe='Ethereal Metal Rings',
        Trivial=212,
        Yield=1,
        Materials={'File','Brick of Ethereal Energy','Ethereal Temper'},
        Container='Forge',
        Tradeskill='Blacksmithing',
    },
    ['Shaded Kunai'] = {
        Recipe='Shaded Kunai',
        Trivial=215,
        Yield=5,
        Materials={'Throwing Knife Mold','Metal Tempering Chemicals','Rhenium Ore'},
        Container='Forge',
        Tradeskill='Blacksmithing',
    },
    ['Indium Plate Gauntlet Template'] = {
        Recipe='Indium Plate Gauntlet Template',
        Trivial=236,
        Yield=1,
        Materials={'Dark Brown Coal','Smithy Hammer','Plate Gauntlet Template Mold','Metal Tempering Chemicals','Indium Ore'},
        Container='Forge',
        Tradeskill='Blacksmithing',
    },
    ['Rhenium Plate Gauntlet Template'] = {
        Recipe='Rhenium Plate Gauntlet Template',
        Trivial=274,
        Yield=1,
        Materials={'Black Nitrous Coal','Smithy Hammer','Plate Gauntlet Template Mold','Metal Tempering Chemicals','Rhenium Ore'},
        Container='Forge',
        Tradeskill='Blacksmithing',
    },
    ['Tungsten Plate Gorget Template'] = {
        Recipe='Tungsten Plate Gorget Template',
        Trivial=310,
        Yield=1,
        Materials={'Lustrous Black Coal','Smithy Hammer','Plate Gorget Template Mold','Metal Tempering Chemicals','Tungsten Ore'},
        Container='Forge',
        Tradeskill='Blacksmithing',
    },
    ['Cobalt Plate Gorget Template'] = {
        Recipe='Cobalt Plate Gorget Template',
        Trivial=348,
        Yield=1,
        Materials={'Toluene Coal','Smithy Hammer','Plate Gorget Template Mold','Metal Tempering Chemicals','Cobalt Ore'},
        Container='Forge',
        Tradeskill='Blacksmithing',
    },
    ['Magic Metal Alloy'] = {
        Recipe='Magic Metal Alloy',
        Trivial=245,
        Yield=1,
        Materials={'Cobalt Ore','Enchanted Platinum Bar','Vial of Purified Mana'},
        Container='Forge',
        Tradeskill='Blacksmithing',
    },
    ['Magic Alloy Sheet'] = {
        Recipe='Magic Alloy Sheet',
        Trivial=245,
        Yield=1,
        Materials={'Smithy Hammer','Magic Metal Alloy'},
        Container='Forge',
        Tradeskill='Blacksmithing',
    },
    ['Enchanted Alloy Whittling Blade'] = {
        Recipe='Enchanted Alloy Whittling Blade',
        Trivial=300,
        Yield=1,
        Materials={'Magic Alloy Sheet','Vial of Purified Mana','Knife Blade Mold','Hilt Mold','Pommel Mold'},
        Container='Forge',
        Tradeskill='Blacksmithing',
    },
    ['Ethereal Temper'] = {
        Recipe='Ethereal Temper',
        Trivial=212,
        Materials={'Celestial Essence','Soda','Emerald Tea Leaf'},
        Container='Brew Barrel',
        Tradeskill='Brewing',
    },
    ['Medium Quality Folded Sheet Metal'] = {
        Recipe='Medium Quality Folded Sheet Metal',
        Trivial=36,
        Materials={'Block of Medium Quality Ore','Water Flask','Smithy Hammer'},
        Container='Forge',
        Tradeskill='Blacksmithing',
    },
}
local materials = {
    ['Celestial Solvent']={Location='',SourceType='Vendor'},
    ['The Scent of Marr']={Location='',SourceType='Vendor'},
    ['Elven Wine']={Location='',SourceType='Vendor'},
    ['Mistletoe']={Location='',SourceType='Vendor'},
    ['Jar of Acid']={Location='',SourceType='Vendor'},
    ['Imbued Emerald']={Location='Tunare Deity',SourceType='Summoned'},
    ['Ruby']={Location='',SourceType='Vendor'},
    ['Smithy Hammer']={Location='Blacksmith Gerta',SourceType='Crafted',Tool=true},
    ['Sheet Metal']={Location='Blacksmith Gerta',SourceType='Vendor'},
    ['Hilt Mold']={Location='Blacksmith Gerta',SourceType='Vendor'},
    ['Sapphire']={Location='',SourceType='Vendor'},
    ['Pommel Mold']={Location='',SourceType='Vendor'},
    ['Emerald']={Location='',SourceType='Vendor'},
    ['Curved Blade Mold']={Location='Blacksmith Gerta',SourceType='Vendor'},
    ['Water Flask']={Location='Blacksmith Gerta',SourceType='Vendor'},
    ['Gorget Mold']={Location='Blacksmith Gerta',SourceType='Vendor'},
    ['Mail Sectional Mold']={Location='Blacksmith Gerta',SourceType='Vendor'},
    ['Rubicite Ore']={Location='',SourceType='Dropped'},
    ['File']={Location='Blacksmithing',SourceType='Crafted',Tool=true},
    ['Leather Padding']={Location='',SourceType='Crafted'},
    ['Plate Visor Mold']={Location='Blacksmith Gerta',SourceType='Vendor'},
    ['Breastplate Mold']={Location='Blacksmith Gerta',SourceType='Vendor'},
    ['Brown Nitrous Coal']={Location='Blacksmith Gerta',SourceType='Vendor'},
    ['Plate Gauntlet Template Mold']={Location='Blacksmith Gerta',SourceType='Vendor'},
    ['Metal Tempering Chemicals']={Location='Blacksmith Gerta',SourceType='Vendor'},
    ['Brick of Ethereal Energy']={Location='',SourceType='Dropped'},
    ['Ethereal Temper']={Location='',SourceType='Crafted'},
    ['Dark Brown Coal']={Location='Blacksmith Gerta',SourceType='Vendor'},
    ['Indium Ore']={Location='',SourceType='Dropped'},
    ['Black Nitrous Coal']={Location='Blacksmith Gerta',SourceType='Vendor'},
    ['Rhenium Ore']={Location='HC Low-Mid',SourceType='Dropped'},
    ['Lustrous Black Coal']={Location='Blacksmith Gerta',SourceType='Vendor'},
    ['Tungsten Ore']={Location='',SourceType='Dropped'},
    ['Plate Gorget Template Mold']={Location='Blacksmith Gerta',SourceType='Vendor'},
    ['Toluene Coal']={Location='Blacksmith Gerta',SourceType='Vendor'},
    ['Cobalt Ore']={Location='',SourceType='Dropped'},
    ['Throwing Knife Mold']={Location='Blacksmith Gerta',SourceType='Vendor'},
    ['Enchanted Platinum Bar']={Location='Enchanter',SourceType='Summoned'},
    ['Vial of Purified Mana']={Location='',SourceType='Crafted'},
    ['Knife Blade Mold']={Location='Blacksmith Gerta',SourceType='Vendor'},
    ['Soda'] = {Location='Caden Zharik',SourceType='Vendor'},
    ['Emerald Tea Leaf'] = {Location='Brewmaster Berina',SourceType='Vendor'},
}
return {
    ['Tabs'] = {'Blacksmithing'},
    ['Blacksmithing'] = recipes,
    ['Materials'] = materials,
    ['Subcombines'] = subcombines,
    ['Stations'] = {
        ['poknowledge'] = {
            ['Pottery Wheel'] = '-288.50 780.29 -91.34',
            ['Kiln'] = '-346.99 796.83 -91.34',
            ['Oven'] = '-346.22 775.99 -91.34',
            ['Forge'] = '-343.74 760.84 -91.34',
            ['Loom'] = '-337.39 924.73 -91.78',
            ['Brew Barrel'] = '-315.00 969.43 -91.89',
        },
    },
}