local recipes = {
    {
        Recipe='Leveling 1 to 135',
        Trivial=135,
        Materials={'Class 3 Wood Point Arrow', 'Class 1 Wood Hooked Arrow','Class 4 Wood Point Arrow','Class 1 Ceramic Point Arrow'},
        Container='Fletching Kit',
        Tradeskill='Fletching',
    },
    {
        Recipe='Epic 1.5',
        Trivial=15,
        Materials={'Large Butterfly Net','Eight-loop Lasso','Twitching Swordfish Blood Sample'},
        Container='Planar Fletching Kit',
        Tradeskill='Fletching',
    },
    {
        Recipe='Classic 135-202',
        Trivial=202,
        Materials={'Class 5 Wood Point Arrow','Class 1 Wood Silver Tip Arrow','Class 1 Steel Point Arrow'},
        Container='Fletching Kit',
        Tradeskill='Fletching',
    },
    {
        Recipe='Discord 135-255',
        Trivial=255,
        Materials={'Class 1 Wood Serrated Tip Arrow','Class 4 Wood Serrated Tip Arrow','Class 1 Steel Serrated Tip Arrow (Large Groove)','Class 1 Steel Discord Tip Arrow (Large Groove)','Class 4 Ceramic Discord Tip Arrow (Medium Groove)'},
        Container='Fletching Kit',
        Tradeskill='Fletching',
    },
    {
        Recipe='Final Push',
        Trivial=335,
        Materials={'Mithril Champion Arrows'},
        Container='Fletching Kit',
        Tradeskill='Fletching',
    },
    {
        Recipe='Heartshot + Heartslit arrows',
        Trivial=182,
        Materials={'Class 3 Wood Silver Tip Arrow'},
        Container='Fletching Kit',
        Tradeskill='Fletching',
    },
}
local subcombines = {
    ['Class 3 Wood Point Arrow'] = {
        Recipe='Class 3 Wood Point Arrow',
        Trivial=82,
        Materials={'Large Groove Nocks','Field Point Arrowheads','Bundled Wooden Arrow Shafts','Several Shield Cut Fletchings'},
        Container='Fletching Kit',
        Tradeskill='Fletching',
    },
    ['Class 1 Wood Hooked Arrow'] = {
        Recipe='Class 1 Wood Hooked Arrow',
        Trivial=102,
        Materials={'Large Groove Nocks','Hooked Arrowheads','Bundled Wooden Arrow Shafts','Several Round Cut Fletchings'},
        Container='Fletching Kit',
        Tradeskill='Fletching',
    },
    ['Class 4 Wood Point Arrow'] = {
        Recipe='Class 4 Wood Point Arrow',
        Trivial=122,
        Materials={'Large Groove Nocks','Field Point Arrowheads','Bundled Wooden Arrow Shafts','Set of Wooden Arrow Vanes'},
        Container='Fletching Kit',
        Tradeskill='Fletching',
    },
    ['Class 1 Ceramic Point Arrow'] = {
        Recipe='Class 1 Ceramic Point Arrow',
        Trivial=135,
        Materials={'Large Groove Nocks','Field Point Arrowheads','Bundled Ceramic Arrow Shafts','Several Round Cut Fletchings'},
        Container='Fletching Kit',
        Tradeskill='Fletching',
    },
    ['Large Butterfly Net'] = {
        Recipe='Large Butterfly Net',
        Trivial=135,
        Materials={'Long Net Pole','Phase Netting'},
        Container='Planar Fletching Kit',
        Tradeskill='Fletching',
    },
    ['Long Net Pole'] = {
        Recipe='Long Net Pole',
        Trivial=15,
        Materials={'Whittling Knife','Fallen Tree Branch'},
        Container='Planar Fletching Kit',
        Tradeskill='Fletching',
    },
    ['Phase Netting'] = {
        Recipe='Phase Netting',
        Trivial=15,
        Materials={'Phase Spider Silk','Phase Spider Silk','Phase Spider Silk','Phase Spider Silk','Pine Sap'},
        Container='Planar Fletching Kit',
        Tradeskill='Fletching',
    },
    ['Eight-loop Lasso'] = {
        Recipe='Eight-loop Lasso',
        Trivial=15,
        Materials={'Fibrous Rope','Fibrous Rope','Fibrous Rope','Fibrous Rope','Fibrous Rope','Fibrous Rope','Fibrous Rope','Fibrous Rope'},
        Container='Planar Fletching Kit',
        Tradeskill='Fletching',
    },
    ['Fibrous Rope'] = {
        Recipe='Fibrous Rope',
        Trivial=15,
        Materials={'Smithy Hammer','Golanda Nut'},
        Container='Planar Fletching Kit',
        Tradeskill='Fletching',
    },
    ['Twitching Swordfish Blood Sample'] = {
        Recipe='Twitching Swordfish Blood Sample',
        Trivial=15,
        Materials={'Magical Sample Vial','Captured Swordfish'},
        Container='Planar Fletching Kit',
        Tradeskill='Fletching',
    },
    ['Class 5 Wood Point Arrow'] = {
        Recipe='Class 5 Wood Point Arrow',
        Trivial=162,
        Yield=5,
        Materials={'Large Groove Nocks','Field Point Arrowheads','Bundled Wooden Arrow Shafts','Set of Bone Arrow Vanes'},
        Container='Fletching Kit',
        Tradeskill='Fletching',
    },
    ['Class 3 Wood Silver Tip Arrow'] = {
        Recipe='Class 3 Wood Silver Tip Arrow',
        Trivial=182,
        Yield=10,
        Materials={'Small Groove Nocks','Silver Tipped Arrowheads','Bundled Wooden Arrow Shafts','Several Shield Cut Fletchings'},
        Container='Fletching Kit',
        Tradeskill='Fletching',
    },
    ['Class 1 Wood Silver Tip Arrow'] = {
        Recipe='Class 1 Wood Silver Tip Arrow',
        Trivial=182,
        Yield=10,
        Materials={'Large Groove Nocks','Silver Tipped Arrowheads','Bundled Wooden Arrow Shafts','Several Round Cut Fletchings'},
        Container='Fletching Kit',
        Tradeskill='Fletching',
    },
    ['Class 1 Steel Point Arrow'] = {
        Recipe='Class 1 Steel Point Arrow',
        Trivial=202,
        Yield=5,
        Materials={'Large Groove Nocks','Field Point Arrowheads','Bundled Steel Arrow Shafts','Several Round Cut Fletchings'},
        Container='Fletching Kit',
        Tradeskill='Fletching',
    },
    ['Taelosian Stone'] = {
        Recipe='Taelosian Stone',
        Trivial=15,
        Yield=1,
        Materials={'Chunk of Taelosian Rock'},
        Container='Fletching Kit',
        Tradeskill='Fletching',
    },
    ['Serrated Arrowhead'] = {
        Recipe='Serrated Arrowhead',
        Trivial=188,
        Yield=2,
        Materials={'File','Water Flask','Taelosian Stone'},
        Container='Fletching Kit',
        Tradeskill='Fletching',
    },
    ['Discord Stone'] = {
        Recipe='Discord Stone',
        Trivial=15,
        Yield=1,
        Materials={'Chunk of Discordian Rock'},
        Container='Fletching Kit',
        Tradeskill='Fletching',
    },
    ['Discord Arrowhead'] = {
        Recipe='Discord Arrowhead',
        Trivial=202,
        Yield=2,
        Materials={'File','Water Flask','Discord Stone'},
        Container='Fletching Kit',
        Tradeskill='Fletching',
    },
    ['Class 1 Wood Serrated Tip Arrow'] = {
        Recipe='Class 1 Wood Serrated Tip Arrow',
        Trivial=202,
        Yield=10,
        Materials={'Large Groove Nocks','Bundled Wooden Arrow Shafts','Several Round Cut Fletchings','Serrated Arrowhead'},
        Container='Fletching Kit',
        Tradeskill='Fletching',
    },
    ['Class 4 Wood Serrated Tip Arrow'] = {
        Recipe='Class 4 Wood Serrated Tip Arrow',
        Trivial=212,
        Yield=10,
        Materials={'Large Groove Nocks','Bundled Wooden Arrow Shafts','Set of Wooden Arrow Vanes','Serrated Arrowhead'},
        Container='Fletching Kit',
        Tradeskill='Fletching',
    },
    ['Class 1 Steel Serrated Tip Arrow (Large Groove)'] = {
        Recipe='Class 1 Steel Serrated Tip Arrow (Large Groove)',
        Trivial=227,
        Yield=1,
        Materials={'Large Groove Nocks','Bundled Steel Arrow Shafts','Several Round Cut Fletchings','Serrated Arrowhead'},
        Container='Fletching Kit',
        Tradeskill='Fletching',
    },
    ['Class 1 Steel Discord Tip Arrow (Large Groove)'] = {
        Recipe='Class 1 Steel Discord Tip Arrow (Large Groove)',
        Trivial=227,
        Yield=10,
        Materials={'Large Groove Nocks','Bundled Steel Arrow Shafts','Several Round Cut Fletchings','Discord Arrowhead'},
        Container='Fletching Kit',
        Tradeskill='Fletching',
    },
    ['Class 4 Ceramic Discord Tip Arrow (Medium Groove)'] = {
        Recipe='Class 4 Ceramic Discord Tip Arrow (Medium Groove)',
        Trivial=255,
        Yield=10,
        Materials={'Medium Groove Nocks','Bundled Ceramic Arrow Shafts','Set of Wooden Arrow Vanes','Discord Arrowhead'},
        Container='Fletching Kit',
        Tradeskill='Fletching',
    },
    ['Mithril Working Knife'] = {
        Recipe='Mithril Working Knife',
        Trivial=42,
        Yield=1,
        Materials={'Small Brick of Mithril','Hilt Mold','Water Flask','Dagger Blade Mold'},
        Container='Forge',
        Tradeskill='Smithing',
    },
    ['Mithril Fletchings'] = {
        Recipe='Mithril Fletchings',
        Trivial=34,
        Yield=2,
        Materials={'Small Brick of Mithril','Mithril Working Knife'},
        Container='Fletching Kit',
        Tradeskill='Fletching',
    },
    ['Mithril Arrow Heads'] = {
        Recipe='Mithril Arrow Heads',
        Trivial=42,
        Yield=2,
        Materials={'Small Brick of Mithril','File','Water Flask'},
        Container='Forge',
        Tradeskill='Smithing',
    },
    ['Mithril Bundled Arrow Shafts'] = {
        Recipe='Mithril Bundled Arrow Shafts',
        Trivial=42,
        Yield=2,
        Materials={'Large Brick of Mithril','Arrow Shaft Mold','File','Water Flask'},
        Container='Forge',
        Tradeskill='Smithing',
    },
    ['Mithril Champion Arrows'] = {
        Recipe='Mithril Champion Arrows',
        Trivial=335,
        Yield=10,
        Materials={'Small Groove Nocks','Mithril Arrow Heads','Mithril Bundled Arrow Shafts','Mithril Fletchings'},
        Container='Fletching Kit',
        Tradeskill='Fletching',
    },
}

local materials = {
    ['Large Groove Nocks']={Location='Fletcher Lenvale',SourceType='Vendor'},
    ['Field Point Arrowheads']={Location='Fletcher Lenvale',SourceType='Vendor'},
    ['Bundled Wooden Arrow Shafts']={Location='Fletcher Lenvale',SourceType='Vendor'},
    ['Several Shield Cut Fletchings']={Location='Fletcher Lenvale',SourceType='Vendor'},
    ['Hooked Arrowheads']={Location='Fletcher Lenvale',SourceType='Vendor'},
    ['Several Round Cut Fletchings']={Location='Fletcher Lenvale',SourceType='Vendor'},
    ['Set of Wooden Arrow Vanes']={Location='Fletcher Lenvale',SourceType='Vendor'},
    ['Bundled Ceramic Arrow Shafts']={Location='Fletcher Lenvale',SourceType='Vendor'},
    ['Whittling Knife']={Location='Yoen Ormard',SourceType='Vendor',Zone='abysmal'},
    ['Fallen Tree Branch']={Location='Dranik\'s Scar',SourceType='Foraging',Zone='draniksscar'},
    ['Golanda Nut']={Location='Dranik\'s Scar',SourceType='Foraging',Zone='draniksscar'},
    ['Phase Spider Silk']={Location='Dragon Necropolis',SourceType='Dropped',Zone='dragonnecropolis'},
    ['Pine Sap']={Location='Surefall Glade',SourceType='Foraging',Zone='surefall'},
    ['Smithy Hammer']={Location='Blacksmith Gerta',SourceType='Vendor'},
    ['Set of Bone Arrow Vanes']={Location='Fletcher Lenvale',SourceType='Vendor'},
    ['Silver Tipped Arrowheads']={Location='Fletcher Lenvale',SourceType='Vendor'},
    ['Bundled Steel Arrow Shafts']={Location='Fletcher Lenvale',SourceType='Vendor'},
    ['Medium Groove Nocks']={Location='Fletcher Lenvale',SourceType='Vendor'},
    ['Chunk of Taelosian Rock']={Location='',SourceType='Dropped'},
    ['Chunk of Discordian Rock']={Location='',SourceType='Dropped'},
    ['File']={Location='',SourceType='Vendor'},
    ['Water Flask']={Location='Blacksmith Gerta',SourceType='Vendor'},
    ['Small Brick of Mithril']={Location='Kelethin or Felwithe',SourceType='Vendor'},
    ['Large Brick of Mithril']={Location='Kelethin or Felwithe',SourceType='Vendor'},
    ['Hilt Mold']={Location='',SourceType='Vendor'},
    ['Dagger Blade Mold']={Location='',SourceType='Vendor'},
    ['Arrow Shaft Mold']={Location='',SourceType='Vendor'},
    ['Small Groove Nocks']={Location='Fletcher Lenvale',SourceType='Vendor'},
}

return {
    ['Tabs'] = {'Fletching'},
    ['Fletching'] = recipes,
    ['Materials'] = materials,
    ['Subcombines'] = subcombines,
    ['Stations'] = {
        ['poknowledge'] = {
            ['Pottery Wheel'] = '-288.50 780.29 -91.34',
            ['Kiln'] = '-346.99 796.83 -91.34',
            ['Oven'] = '-346.22 775.99 -91.34',
            ['Forge'] = '-343.74 760.84 -91.34',
            ['Loom'] = '-337.39 924.73 -91.78',
            ['Brew Barrel'] = '-315.00 969.43 -91.89',
        },
    },
}