return {
    ['Baking'] = {
        {
            Recipe='Fish Rolls',
            Trivial=135,
            Materials={'Fresh Fish','Bat Wing'},
            Container='Oven',
        },
        {
            Recipe='Patty Melt',
            Trivial=190,
            Materials={'Cheese','Non-Stick Frying Pan','Loaf of Bread','Bear Meat'},
            Container='Oven',
        },
        {
            Recipe='Misty Thicket Picnic',
            Trivial=335,
            Materials={'Marmalade Sandwich','Jumjum Salad','Royal Mints','Slice of Jumjum Cake','Slice of Jumjum Cake','Mature Cheese','Picnic Basket','Jumjum Spiced Beer'},
            Container='Oven',
        },
    },
    ['Blacksmithing'] = {
        {
            Recipe='Ethereal Metal Rings',
            Trivial=212,
            Materials={'Brick of Ethereal Energy','Ethereal Temper','File'},
            Container='Forge',
        },
        {
            Recipe='Rhenium Chain Collar Template',
            Trivial=272,
            Materials={'Black Nitrous Coal','Smithy Hammer','Chainmail Collar Template Pattern','Metal Tempering Chemicals','Rhenium Ore'},
            Container='Forge',
        },
        {
            Recipe='Tungsten Chain Collar Template',
            Trivial=310,
            Materials={'Lustrous Black Coal','Smithy Hammer','Chainmail Collar Template Pattern','Metal Tempering Chemicals','Tungsten Ore'},
            Container='Forge',
        },
    },
    ['Brewing'] = {
        {
            Recipe='Fetid Essence',
            Trivial=122,
            Materials={'Water Flask','Fishing Grubs'},
            Container='Brew Barrel',
        },
        {
            Recipe='Minotaur Hero\'s Brew',
            Trivial=248,
            Materials={'Water Flask','Water Flask','Short Beer','Short Beer','Malt','Malt','Malt','Yeast','Cask'},
            Container='Brew Barrel',
        },
        {
            Recipe='Brut Champagne',
            Trivial=335,
            Materials={'Grapes','Grapes','Grapes','Soda Water','Champagne Magnum','Wine Yeast'},
            Container='Brew Barrel',
        },
    },
    ['Fletching'] = {
        {
            Recipe='Class 6 Wood Point Arrow',
            Trivial=202,
            Materials={'Large Groove Nocks','Bundled Wooden Arrow Shafts','Field Point Arrowheads','Set of Ceramic Arrow Vanes'},
            Container='Fletching Kit',
        },
        {
            Recipe='Mithril Champion Arrows',
            Trivial=335,
            Materials={'Mithril Arrow Heads','Mithril Bundled Arrow Shafts','Mithril Fletchings','Small Groove Nocks'},
            Container='Fletching Kit',
        },
    },
    ['Jewelry Making'] = {
        {
            Recipe='Electrum Malachite Bracelet',
            RecipeIndexOffset=1,
            Trivial=74,
            Materials={'Malachite','Electrum Bar'},
            Container='Jeweler\'s Kit',
        },
        {
            Recipe='Electrum Malachite Bracelet',
            Variant='Enchanted',
            Trivial=74,
            Materials={'Malachite','Enchanted Electrum Bar'},
            Container='Jeweler\'s Kit',
        },
        {
            Recipe='Electrum Pearl Choker',
            RecipeIndexOffset=1,
            Trivial=108,
            Materials={'Pearl','Electrum Bar'},
            Container='Jeweler\'s Kit',
        },
        {
            Recipe='Electrum Pearl Choker',
            Variant='Enchanted',
            Trivial=108,
            Materials={'Pearl','Enchanted Electrum Bar'},
            Container='Jeweler\'s Kit',
        },
        {
            Recipe='Gold Malachite Bracelet',
            RecipeIndexOffset=1,
            Trivial=146,
            Materials={'Malachite','Gold Bar'},
            Container='Jeweler\'s Kit',
        },
        {
            Recipe='Gold Malachite Bracelet',
            Variant='Enchanted',
            Trivial=146,
            Materials={'Malachite','Enchanted Gold Bar'},
            Container='Jeweler\'s Kit',
        },
        {
            Recipe='Golden Topaz Earring',
            RecipeIndexOffset=1,
            Trivial=183,
            Materials={'Topaz','Gold Bar'},
            Container='Jeweler\'s Kit',
        },
        {
            Recipe='Golden Topaz Earring',
            Variant='Enchanted',
            Trivial=183,
            Materials={'Topaz','Enchanted Gold Bar'},
            Container='Jeweler\'s Kit',
        },
        {
            Recipe='Golden Opal Amulet',
            RecipeIndexOffset=1,
            Trivial=191,
            Materials={'Opal','Gold Bar'},
            Container='Jeweler\'s Kit',
        },
        {
            Recipe='Golden Opal Amulet',
            Variant='Enchanted',
            Trivial=191,
            Materials={'Opal','Enchanted Gold Bar'},
            Container='Jeweler\'s Kit',
        },
        {
            Recipe='Fire Emerald Golden Bracelet',
            RecipeIndexOffset=1,
            Trivial=202,
            Materials={'Fire Emerald','Gold Bar'},
            Container='Jeweler\'s Kit',
        },
        {
            Recipe='Fire Emerald Golden Bracelet',
            Variant='Enchanted',
            Trivial=202,
            Materials={'Fire Emerald','Enchanted Gold Bar'},
            Container='Jeweler\'s Kit',
        },
        {
            Recipe='Cat Eye Platinum Necklace',
            RecipeIndexOffset=1,
            Trivial=228,
            Materials={'Cat\'s Eye Agate','Platinum Bar'},
            Container='Jeweler\'s Kit',
        },
        {
            Recipe='Cat Eye Platinum Necklace',
            Variant='Enchanted',
            Trivial=228,
            Materials={'Cat\'s Eye Agate','Enchanted Platinum Bar'},
            Container='Jeweler\'s Kit',
        },
        {
            Recipe='Platinum Amber Ring',
            RecipeIndexOffset=2,
            Trivial=244,
            Materials={'Amber','Platinum Bar'},
            Container='Jeweler\'s Kit',
        },
        {
            Recipe='Platinum Amber Ring',
            RecipeIndexOffset=1,
            Variant='Enchanted',
            Trivial=244,
            Materials={'Amber','Enchanted Platinum Bar'},
            Container='Jeweler\'s Kit',
        },
        {
            Recipe='Platinum Topaz Necklace',
            RecipeIndexOffset=2,
            Trivial=255,
            Materials={'Topaz','Platinum Bar'},
            Container='Jeweler\'s Kit',
        },
        {
            Recipe='Platinum Topaz Necklace',
            RecipeIndexOffset=1,
            Variant='Enchanted',
            Trivial=255,
            Materials={'Topaz','Enchanted Platinum Bar'},
            Container='Jeweler\'s Kit',
        },
        {
            Recipe='Platinum Fire Wedding Ring',
            RecipeIndexOffset=1,
            Trivial=268,
            Materials={'Fire Opal','Platinum Bar'},
            Container='Jeweler\'s Kit',
        },
        {
            Recipe='Platinum Fire Wedding Ring',
            Variant='Enchanted',
            Trivial=268,
            Materials={'Fire Opal','Enchanted Platinum Bar'},
            Container='Jeweler\'s Kit',
        },
        {
            Recipe='Sapphire Platinum Necklace',
            RecipeIndexOffset=4,
            Trivial=276,
            Materials={'Sapphire','Platinum Bar'},
            Container='Jeweler\'s Kit',
        },
        {
            Recipe='Sapphire Platinum Necklace',
            RecipeIndexOffset=3,
            Variant='Enchanted',
            Trivial=276,
            Materials={'Sapphire','Enchanted Platinum Bar'},
            Container='Jeweler\'s Kit',
        },
        {
            Recipe='Platinum Diamond Wedding Ring',
            RecipeIndexOffset=1,
            Trivial=287,
            Materials={'Diamond','Platinum Bar'},
            Container='Jeweler\'s Kit',
        },
        {
            Recipe='Platinum Diamond Wedding Ring',
            Variant='Enchanted',
            Trivial=287,
            Materials={'Diamond','Enchanted Platinum Bar'},
            Container='Jeweler\'s Kit',
        },
        {
            Recipe='Platinum Blue Diamond Tiara',
            RecipeIndexOffset=1,
            Trivial=295,
            Materials={'Blue Diamond','Platinum Bar'},
            Container='Jeweler\'s Kit',
        },
        {
            Recipe='Platinum Blue Diamond Tiara',
            Variant='Enchanted',
            Trivial=295,
            Materials={'Blue Diamond','Enchanted Platinum Bar'},
            Container='Jeweler\'s Kit',
        },
        {
            Recipe='Velium Blue Diamond Bracelet',
            RecipeIndexOffset=1,
            Trivial=302,
            Materials={'Blue Diamond','Velium Bar'},
            Container='Jeweler\'s Kit',
        },
        {
            Recipe='Velium Blue Diamond Bracelet',
            Variant='Enchanted',
            Trivial=302,
            Materials={'Blue Diamond','Enchanted Velium Bar'},
            Container='Jeweler\'s Kit',
        },
    },
    ['Pottery'] = {
        {
            Recipe='Sealed Poison Vial (Crow\'s Special Brew)',
            Trivial=188,
            Materials={'Crow\'s Special Brew','Sealed Vial Sketch','Small Block of Clay','Water Flask'},
            Container='Pottery Wheel',
        },
        {
            Recipe='Unfired Idol',
            RecipeIndexOffset=9,
            Trivial=248,
            Materials={'Idol Sketch','Imbued Amber','Large Block of Magic Clay','Sculpting Tools','Vial of Clear Mana'},
            Container='Pottery Wheel',
        },
        {
            Recipe='Unfired Idol',
            RecipeIndexOffset=1,
            Trivial=282,
            Materials={'Idol Sketch','Imbued Emerald','Large Block of Magic Clay','Sculpting Tools','Vial of Clear Mana'},
            Container='Pottery Wheel',
        },
        {
            Recipe='Unfired Star Ruby Encrusted Stein',
            Trivial=335,
            Materials={'Water Flask','Large Block of Magic Clay','Celestial Essence','Ceramic Lining Sketch','Sculpting Tools','Lacquered Star Ruby'},
            Container='Pottery Wheel',
        },
    },
    ['Tailoring'] = {
        {
            Recipe='Ethereal Silk Swatch',
            Trivial=212,
            Materials={'Ethereal Curing Agent','Strand of Ether','Strand of Ether'},
            Container='Loom',
        },
        {
            Recipe='Fine Silk Wristband Template',
            Trivial=272,
            Materials={'Fine Silk','Fine Silk','Soft Filament','Silk Curing Chemicals','Silk Wristband Template Pattern','Simple Sewing Needle'},
            Container='Loom',
        },
        {
            Recipe='Fine Leather Gorget Template',
            Trivial=272,
            Materials={'Fine Animal Pelt','Soft Filament','Tanning Chemicals','Leather Gorget Template Pattern','Simple Sewing Needle'},
            Container='Loom',
        },
        {
            Recipe='Excellent Silk Wristband Template',
            Trivial=310,
            Materials={'Excellent Silk','Excellent Silk','Fine Filament','Silk Curing Chemicals','Silk Wristband Template Pattern','Simple Sewing Needle'},
            Container='Loom',
        },
        {
            Recipe='Excellent Leather Gorget Template',
            Trivial=310,
            Materials={'Excellent Animal Pelt','Fine Filament','Tanning Chemicals','Leather Gorget Template Pattern','Simple Sewing Needle'},
            Container='Loom',
        },
    },
    ['Alchemy'] = {
        {
            Recipe='Elixir of Greater Concentration',
            Trivial=244,
            Materials={'Duskglow Vine','Violet Tri-Tube Sap'},
            Container='Medicine Bag',
        },
        {
            Recipe='Distillate of Divine Healing X',
            Trivial=348,
            Materials={'Nodding Blue Lily','Hemlock Powder','Tregrum','Small Vial','Small Vial','Small Vial','Small Vial','Small Vial'},
            Container='Medicine Bag',
        }
    },
    ['Radix']  = {
        {
            Recipe='Essence Fusion Chamber',
            Trivial=500,
            Materials={'Smithy Hammer', 'Fusion Chamber Base', 'Fusion Chamber Housing', 'Elemental Forging Temper', 'Elemental Forging Temper', 'Ancient Shield of Corrupted Tranquility'},
            Container='Forge',
        },
        {
            Recipe='Globe of Swirling Elements',
            Trivial=0,
            Materials={'Essence of Creation', 'Primal Essence of Air', 'Primal Essence of Earth', 'Primal Essence of Water'},
            Container='Essence Fusion Chamber',
        },
    },
    ['Subcombines'] = {
        -- Radix
        ['Elemental Forging Temper'] = {
            Recipe='Elemental Forging Temper',
            Trivial=400,
            Materials={'Air Mephit Blood', 'Earth Mephit Blood', 'Fire Mephit Blood', 'Water Mephit Blood', 'Celestial Essence'},
            Container='Brew Barrel',
            Tradeskill='Brewing',
        },
        ['Element Imbued Metal Sheet'] = {
            Recipe='Element Imbued Metal Sheet',
            Trivial=450,
            Materials={'Smithy Hammer', 'Energy Permeable Ore', 'Elemental Forging Temper', 'Bituminous Coal'},
            Container='Forge',
            Tradeskill='Blacksmithing',
        },
        ['Fusion Chamber Housing'] = {
            Recipe='Fusion Chamber Housing',
            Trivial=475,
            Materials={'Smithy Hammer', 'Element Imbued Metal Sheet', 'Element Imbued Metal Sheet', 'Element Imbued Metal Sheet', 'Element Imbued Metal Sheet', 'Elemental Forging Temper', 'Elemental Forging Temper'},
            Container='Forge',
            Tradeskill='Blacksmithing',
        },
        ['Fusion Chamber Base'] = {
            Recipe='Fusion Chamber Base',
            Trivial=475,
            Materials={'Smithy Hammer', 'Element Imbued Metal Sheet', 'Element Imbued Metal Sheet', 'Elemental Forging Temper'},
            Container='Forge',
            Tradeskill='Blacksmithing',
        },

        -- Baking
        ['Non-Stick Frying Pan'] = {
            Recipe='Non-Stick Frying Pan',
            Trivial=91,
            Materials={'Frying Pan Mold','Water Flask','Metal Bits','Ceramic Lining'},
            Container='Forge',
            Tradeskill='Blacksmithing',
            Tool=true,
        },
        ['Metal Bits'] = {
            Recipe='Metal Bits',
            Trivial=18,
            Materials={'Small Piece of Ore','Small Piece of Ore','Water Flask'},
            Container='Forge',
            Tradeskill='Blacksmithing',
        },
        ['Ceramic Lining'] = {
            Recipe='Ceramic Lining',
            Trivial=17,
            Materials={'Quality Firing Sheet','Unfired Ceramic Lining'},
            Container='Kiln',
            Tradeskill='Pottery',
        },
        ['Unfired Ceramic Lining'] = {
            Recipe='Unfired Ceramic Lining',
            Trivial=36,
            Materials={'Water Flask','Small Block of Clay','Ceramic Lining Sketch'},
            Container='Pottery Wheel',
            Tradeskill='Pottery',
        },
        ['Marmalade Sandwich'] = {
            Recipe='Marmalade Sandwich',
            Trivial=99,
            Materials={'Apricot Marmalade','Loaf of Bread'},
            Container='Oven',
            Tradeskill='Baking',
        },
        ['Apricot Marmalade'] = {
            Recipe='Apricot Marmalade',
            Trivial=99,
            Materials={'Fruit','Frosting','Frosting','Frosting'},
            Container='Oven',
            Tradeskill='Baking',
        },
        ['Jumjum Salad'] = {
            Recipe='Jumjum Salad',
            Trivial=142,
            Materials={'Fennel','Jumjum Stalk','Vegetables','Lettuce'},
            Container='Mixing Bowl',
            Tradeskill='Baking',
        },
        ['Royal Mints'] = {
            Recipe='Royal Mints',
            Trivial=76,
            Materials={'Eucalyptus Leaf','Frosting'},
            Container='Mixing Bowl',
            Tradeskill='Baking',
        },
        ['Slice of Jumjum Cake'] = {
            Recipe='Slice of Jumjum Cake',
            Trivial=27,
            Materials={'Jumjum Cake'},
            Container='Oven',
            Tradeskill='Baking',
        },
        ['Jumjum Cake'] = {
            Recipe='Jumjum Cake',
            Trivial=166,
            Materials={'Clump of Dough','Jumjum Stalk','Cake Round','Winter Chocolate','Frosting'},
            Container='Oven',
            Tradeskill='Baking',
        },
        ['Clump of Dough'] = {
            Recipe='Clump of Dough',
            Trivial=28,
            Materials={'Basilisk Egg','Bottle of Milk','Cup of Flour'},
            Container='Mixing Bowl',
            Tradeskill='Baking',
        },
        ['Cake Round'] = {
            Recipe='Cake Round',
            Trivial=37,
            Materials={'Water Flask','Metal Bits','Cake Round Mold','Ceramic Lining'},
            Container='Forge',
            Tradeskill='Blacksmithing',
        },
        ['Winter Chocolate'] = {
            Recipe='Winter Chocolate',
            Trivial=95,
            Materials={'Brownie Parts','Frosting','Frosting'},
            Container='Mixing Bowl',
            Tradeskill='Baking',
        },
        ['Mature Cheese'] = {
            Recipe='Mature Cheese',
            Trivial=84,
            Materials={'Bottle of Milk','Bottle of Milk','Dairy Spoon','Rennet'},
            Container='Mixing Bowl',
            Tradeskill='Baking',
        },
        ['Dairy Spoon'] = {
            Recipe='Dairy Spoon',
            Trivial=74,
            Materials={'Water Flask','Metal Bits','Metal Bits','Scaler Mold'},
            Container='Forge',
            Tradeskill='Blacksmithing',
            Tool=true,
        },
        ['Picnic Basket'] = {
            Recipe='Picnic Basket',
            Trivial=76,
            Materials={'Woven Mandrake','Steel Boning'},
            Container='Loom',
            Tradeskill='Tailoring',
        },
        ['Woven Mandrake'] = {
            Recipe='Woven Mandrake',
            Trivial=66,
            Materials={'Mandrake Root','Mandrake Root'},
            Container='Loom',
            Tradeskill='Tailoring',
        },
        ['Steel Boning'] = {
            Recipe='Steel Boning',
            Trivial=37,
            Materials={'Water Flask','File','Small Brick of Ore'},
            Container='Forge',
            Tradeskill='Blacksmithing',
        },
        ['Jumjum Spiced Beer'] = {
            Recipe='Jumjum Spiced Beer',
            Trivial=162,
            Materials={'Water Flask','Spices','Jumjum Stalk','Bottle','Barley','Hops'},
            Container='Brew Barrel',
            Tradeskill='Brewing',
        },
        ['Vegetables'] = {
            Recipe='Vegetables',
            Trivial=15,
            Materials={'Lettuce','Carrot','Turnip'},
            Container='Mixing Bowl',
            Tradeskill='Baking',
        },
        -- Blacksmithing
        ['Ethereal Temper'] = {
            Recipe='Ethereal Temper',
            Trivial=212,
            Materials={'Celestial Essence','Soda','Emerald Tea Leaf'},
            Container='Brew Barrel',
            Tradeskill='Brewing',
        },
        ['Soda Water'] = {
            Recipe='Soda Water',
            Trivial=58,
            Materials={'Soda','Water Flask'},
            Container='Brew Barrel',
            Tradeskill='Brewing',
        },
        -- Brewing
        ['Champagne Magnum'] = {
            Recipe='Champagne Magnum',
            Trivial=196,
            Materials={'Opal','Enchanted Gold Bar','Bottle'},
            Container='Jeweler\'s Kit',
            Tradeskill='Jewelry Making',
        },
        -- Fletching
        ['Mithril Arrow Heads'] = {
            Recipe='Mithril Arrow Heads',
            Trivial=42,
            Materials={'Small Brick of Mithril','File','Water Flask'},
            Container='Feir`Dal Forge',
            Tradeskill='Blacksmithing',
        },
        ['Mithril Bundled Arrow Shafts'] = {
            Recipe='Mithril Bundled Arrow Shafts',
            Trivial=42,
            Materials={'Large Brick of Mithril','Arrow Shaft Mold','File','Water Flask'},
            Container='Feir`Dal Forge',
            Tradeskill='Blacksmithing',
        },
        ['Mithril Fletchings'] = {
            Recipe='Mithril Fletchings',
            Trivial=34,
            Materials={'Small Brick of Mithril','Mithril Working Knife'},
            Container='Feir`Dal Fletching Kit',
            Tradeskill='Fletching',
        },
        ['Mithril Working Knife'] = {
            Recipe='Mithril Working Knife',
            Trivial=42,
            Materials={'Small Brick of Mithril','Hilt Mold','Water Flask','Dagger Blade Mold'},
            Container='Feir`Dal Forge',
            Tradeskill='Blacksmithing',
            Tool=true,
        },
        -- Tailoring
        ['Ethereal Curing Agent'] = {
            Recipe='Ethereal Curing Agent',
            Trivial=212,
            Materials={'Celestial Essence','Celestial Essence','Soda','Packet of Paeala Sap'},
            Container='Brew Barrel',
            Tradeskill='Brewing',
        },
        -- Pottery
        ['Lacquered Star Ruby'] = {
            Recipe='Lacquered Star Ruby',
            Trivial=128,
            Materials={'Jar of Lacquer','Star Ruby'},
            Container='Jeweler\'s Kit',
            Tradeskill='Jewelry Making',
        },
        -- General
        ['Celestial Essence'] = {
            Recipe='Celestial Essence',
            Trivial=15,
            Materials={'Concentrated Celestial Solvent','The Scent of Marr','The Scent of Marr','The Scent of Marr'},
            Container='Mixing Bowl',
            Tradeskill='Baking',
        },
        ['File'] = {
            Recipe='File',
            Trivial=21,
            Materials={'File Mold','Metal Bits','Water Flask'},
            Container='Forge',
            Tradeskill='Blacksmithing',
            Tool=true,
        },
    },
    ['Materials'] = {
        -- Radix
        ['Air Mephit Blood']={Location='PoAir',SourceType='Dropped'},
        ['Earth Mephit Blood']={Location='PoEarth',SourceType='Dropped'},
        ['Fire Mephit Blood']={Location='PoFire',SourceType='Dropped'},
        ['Water Mephit Blood']={Location='PoWater',SourceType='Dropped'},
        ['Energy Permeable Ore']={Location='Ssra',SourceType='Ground Spawn'},
        ['Bituminous Coal']={Location='Borik Darkanvil',SourceType='Vendor'},
        ['Ancient Shield of Corrupted Tranquility']={Location='Quarm/FUKU',SourceType='Dropped'},
        ['Essence of Creation']={Location='Drosal',SourceType='Max Tradeskills'},
        ['Primal Essence of Air']={Location='Quest',SourceType='Quest'},
        ['Primal Essence of Earth']={Location='Drosal',SourceType='Quest'},
        ['Primal Essence of Water']={Location='Drosal',SourceType='Quest'},
        -- Tools
        ['Smithy Hammer'] = {Location='Borik Darkanvil',SourceType='Vendor',Tool=true},
        ['Sculpting Tools'] = {Location='Sculptor Radee',SourceType='Vendor',Tool=true},
        ['Simple Sewing Needle'] = {Location='Sherin Matrick',SourceType='Vendor',Tool=true},
        -- Baking
        ['Fresh Fish'] = {Location='Klen Ironstove',SourceType='Vendor'},
        ['Bat Wing'] = {Location='Darius Gandril',SourceType='Vendor',Zone='poknowledge'},
        ['Cheese'] = {Location='Klen Ironstove',SourceType='Vendor'},
        ['Loaf of Bread'] = {Location='Klen Ironstove',SourceType='Vendor'},
        ['Bear Meat'] = {Location='Klen Ironstove',SourceType='Vendor'},
        -- Blacksmithing
        ['Brick of Ethereal Energy'] = {Location='Planes of Power',SourceType='Dropped'},
        ['Black Nitrous Coal'] = {Location='Zosran Hammertail',SourceType='Vendor'},
        ['Chainmail Collar Template Pattern'] = {Location='Borik Darkanvil',SourceType='Vendor'},
        ['Metal Tempering Chemicals'] = {Location='Zosran Hammertail',SourceType='Vendor'},
        ['Rhenium Ore'] = {Location='HC Low-Mid',SourceType='Dropped'},
        ['Lustrous Black Coal'] = {Location='Borik Darkanvil',SourceType='Vendor'},
        ['Tungsten Ore'] = {Location='HC Mid-High',SourceType='Dropped'},
        ['Water Flask'] = {Location='Klen Ironstove',SourceType='Vendor'},
        -- Brewing
        ['Fishing Grubs'] = {Location='Caden Zharik',SourceType='Vendor'},
        ['Short Beer'] = {Location='Brewmaster Berina',SourceType='Vendor'},
        ['Malt'] = {Location='Brewmaster Berina',SourceType='Vendor'},
        ['Cask'] = {Location='Brewmaster Berina',SourceType='Vendor'},
        ['Yeast'] = {Location='Brewmaster Berina',SourceType='Vendor'},
        ['Grapes'] = {Location='Brewmaster Berina',SourceType='Vendor'},
        ['Wine Yeast'] = {Location='Brewmaster Berina',SourceType='Vendor'},
        -- Fletching
        ['Large Groove Nocks'] = {Location='Fletcher Lenvale',SourceType='Vendor'},
        ['Bundled Wooden Arrow Shafts'] = {Location='Fletcher Lenvale',SourceType='Vendor'},
        ['Field Point Arrowheads'] = {Location='Fletcher Lenvale',SourceType='Vendor'},
        ['Set of Ceramic Arrow Vanes'] = {Location='Fletcher Lenvale',SourceType='Vendor'},
        ['Small Groove Nocks'] = {Location='Fletcher Lenvale',SourceType='Vendor'},
        ['Arrow Shaft Mold'] = {Location='Fletcher Lenvale',SourceType='Vendor'},
        ['Small Brick of Mithril'] = {Location='Merchant Niwiny',SourceType='Vendor',Zone='gfaydark'},
        ['Large Brick of Mithril'] = {Location='Merchant Niwiny',SourceType='Vendor',Zone='gfaydark'},
        -- Jewelry Making
        ['Malachite'] = {Location='Audri Deepfacet',SourceType='Vendor'},
        ['Pearl'] = {Location='Audri Deepfacet',SourceType='Vendor'},
        ['Topaz'] = {Location='Audri Deepfacet',SourceType='Vendor'},
        ['Opal'] = {Location='Audri Deepfacet',SourceType='Vendor'},
        ['Fire Emerald'] = {Location='Elemental+',SourceType='Dropped'},
        ['Cat\'s Eye Agate'] = {Location='Audri Deepfacet',SourceType='Vendor'},
        ['Amber'] = {Location='Audri Deepfacet',SourceType='Vendor'},
        ['Fire Opal'] = {Location='Audri Deepfacet',SourceType='Vendor'},
        ['Star Ruby'] = {Location='Elemental+',SourceType='Dropped'},
        ['Sapphire'] = {Location='Elemental+',SourceType='Dropped'},
        ['Diamond'] = {Location='Elemental+',SourceType='Dropped'},
        ['Blue Diamond'] = {Location='Elemental+',SourceType='Dropped'},
        ['Electrum Bar'] = {Location='Audri Deepfacet',SourceType='Vendor'},
        ['Gold Bar'] = {Location='Audri Deepfacet',SourceType='Vendor'},
        ['Platinum Bar'] = {Location='Audri Deepfacet',SourceType='Vendor'},
        ['Velium Bar'] = {Location='Talem Tucter',SourceType='Vendor',Zone='thurgadina'},
        ['Enchanted Electrum Bar'] = {Location='Enchanter',SourceType='Summoned'},
        ['Enchanted Gold Bar'] = {Location='Enchanter',SourceType='Summoned'},
        ['Enchanted Platinum Bar'] = {Location='Enchanter',SourceType='Summoned'},
        ['Enchanted Velium Bar'] = {Location='Enchanter',SourceType='Summoned'},
        -- Pottery
        ['Crow\'s Special Brew'] = {Location='Sculptor Radee',SourceType='Vendor'},
        ['Sealed Vial Sketch'] = {Location='Sculptor Radee',SourceType='Vendor'},
        ['Small Block of Clay'] = {Location='Sculptor Radee',SourceType='Vendor'},
        ['Idol Sketch'] = {Location='Sculptor Radee',SourceType='Vendor'},
        ['Imbued Amber'] = {Location='Cazic Thule Deity',SourceType='Summoned'},
        ['Large Block of Magic Clay'] = {Location='Enchanter',SourceType='Summoned'},
        ['Vial of Clear Mana'] = {Location='Enchanter',SourceType='Summoned'},
        ['Imbued Emerald'] = {Location='Tunare Deity',SourceType='Summoned'},
        ['Ceramic Lining Sketch'] = {Location='Sculptor Radee',SourceType='Vendor'},
        ['Jar of Lacquer'] = {Location='Borik Darkanvil',SourceType='Vendor'},
        -- Tailoring
        ['Packet of Paeala Sap'] = {Location='Brewmaster Berina',SourceType='Vendor'},
        ['Strand of Ether'] = {Location='Planes',SourceType='Dropped'},
        ['Fine Silk'] = {Location='HC Low-Mid',SourceType='Dropped'},
        ['Fine Animal Pelt'] = {Location='HC Low-Mid',SourceType='Dropped'},
        ['Excellent Animal Pelt'] = {Location='HC Low-Mid',SourceType='Dropped'},
        ['Soft Filament'] = {Location='Sherin Matrick',SourceType='Vendor'},
        ['Silk Curing Chemicals'] = {Location='Sherin Matrick',SourceType='Vendor'},
        ['Tanning Chemicals'] = {Location='Sherin Matrick',SourceType='Vendor'},
        ['Silk Wristband Template Pattern'] = {Location='Sherin Matrick',SourceType='Vendor'},
        ['Leather Gorget Template Pattern'] = {Location='Sherin Matrick',SourceType='Vendor'},
        ['Excellent Silk'] = {Location='HC Mid-High',SourceType='Dropped'},
        ['Fine Filament'] = {Location='Sherin Matrick',SourceType='Vendor'},
        -- Picnics
        ['Frying Pan Mold'] = {Location='Roghur Muleson',SourceType='Vendor',Zone='freeporteast'},
        ['Small Piece of Ore'] = {Location='Sculptor Radee',SourceType='Vendor'},
        ['Quality Firing Sheet'] = {Location='Sculptor Radee',SourceType='Vendor'},
        ['Fruit'] = {Location='Anywhere',SourceType='Foraged'},
        ['Frosting'] = {Location='Klen Ironstove',SourceType='Vendor'},
        ['Fennel'] = {Location='Klen Ironstove',SourceType='Vendor'},
        ['Jumjum Stalk'] = {Location='Klen Ironstove',SourceType='Vendor'},
        ['Carrot'] = {Location='Klen Ironstove',SourceType='Vendor'},
        ['Turnip'] = {Location='Klen Ironstove',SourceType='Vendor'},
        ['Lettuce'] = {Location='Klen Ironstove',SourceType='Vendor'},
        ['Eucalyptus Leaf'] = {Location='Alchemist Redsa',SourceType='Vendor'},
        ['Basilisk Eggs'] = {Location='A Shady Merchant',SourceType='Vendor'},
        ['Bottle of Milk'] = {Location='Klen Ironstove',SourceType='Vendor'},
        ['Cup of Flour'] = {Location='Klen Ironstove',SourceType='Vendor'},
        ['Cake Round Mold'] = {Location='Klen Ironstove',SourceType='Vendor'},
        ['Brownie Parts'] = {Location='Lesser Faydark',SourceType='Dropped'},
        ['Rennet'] = {Location='Klen Ironstove',SourceType='Vendor'},
        ['Scaler Mold'] = {Location='Klen Ironstove',SourceType='Vendor'},
        ['Mandrake Root'] = {Location='Alchemist Redsa',SourceType='Vendor'},
        ['Small Brick of Ore'] = {Location='Borik Darkanvil',SourceType='Vendor'},
        ['Spices'] = {Location='Brewmaster Berina',SourceType='Vendor'},
        ['Bottle'] = {Location='Brewmaster Berina',SourceType='Vendor'},
        ['Barley'] = {Location='Brewmaster Berina',SourceType='Vendor'},
        ['Hops'] = {Location='Brewmaster Berina',SourceType='Vendor'},
        ['Soda'] = {Location='Caden Zharik',SourceType='Vendor'},
        ['Emerald Tea Leaf'] = {Location='Brewmaster Berina',SourceType='Vendor'},
        ['Hilt Mold'] = {Location='Borik Darkanvil',SourceType='Vendor'},
        ['File Mold'] = {Location='Borik Darkanvil',SourceType='Vendor'},
        ['Dagger Blade Mold'] = {Location='Borik Darkanvil',SourceType='Vendor'},
        -- Alchemy
        ['Duskglow Vine'] = {Location='Alchemist Redsa',SourceType='Vendor'},
        ['Violet Tri-Tube Sap'] = {Location='Alchemist Redsa',SourceType='Vendor'},
        ['Tregrum'] = {Location='Alchemist Redsa',SourceType='Vendor'},
        ['Nodding Blue Lily']={Location='HC zones',SourceType='Dropped'},
        ['Small Vial']={Location='Alchemist Redsa',SourceType='Vendor'},
        ['Hemlock Powder']={Location='Alchemist Redsa',SourceType='Vendor'},
        -- General
        ['Concentrated Celestial Solvent'] = {Location='Darius Gandril',SourceType='Vendor',Zone='poknowledge'},
        ['The Scent of Marr'] = {Location='Toxicologist Huey',SourceType='Vendor'},
        -- Containers
        ['Fletching Kit'] = {Location='Fletcher Lenvale',SourceType='Vendor',Container=true},
        ['Jeweler\'s Kit'] = {Location='Audri Deepfacet',SourceType='Vendor',Container=true},
        ['Medicine Bag'] = {Location='Alchemist Redsa',SourceType='Vendor',Container=true},
    },
    ['Stations'] = {
        ['poknowledge'] = {
            ['Pottery Wheel'] = '-288.50 780.29 -91.34',
            ['Kiln'] = '-346.99 796.83 -91.34',
            ['Oven'] = '-346.22 775.99 -91.34',
            ['Forge'] = '-343.74 760.84 -91.34',
            ['Loom'] = '-337.39 924.73 -91.78',
            ['Brew Barrel'] = '-315.00 969.43 -91.89',
        },
        ['freeporttemple'] = {
            ['Pottery Wheel'] = '646 -68 -52',
            ['Kiln'] = '585 -62 -52',
            ['Oven'] = '584 66 -52',
            ['Forge'] = '802 55 -52',
            ['Loom'] = '650 64 -52',
            ['Brew Barrel'] = '800 -53 -52',
        },
        ['guildhall'] = {
            ['Pottery Wheel'] = '-16.73 99.56 4.30',
            ['Kiln'] = '16.68 101.11 4.30',
            ['Oven'] = '-56.40 80.69 4.30',
            ['Forge'] = '-39.02 109.22 4.30',
            ['Loom'] = '58.21 92.37 4.30',
            ['Brew Barrel'] = '33.07 113.01 4.30',
        },
        ['gfaydark'] = {
            ['Feir`Dal Forge'] = '-245 61 118',
        },
    },
    ['Tabs'] = {'Baking','Blacksmithing','Brewing','Fletching','Jewelry Making','Pottery','Tailoring','Alchemy'},
}